### ISSUE TITLE
Vscode-sqltools cannot connect to mysql 8.0.x.

### ISSUE THREAD

**Issue by qwfys** [mtxr/vscode-sqltools#279]
**Describe the bug**

In the Spring boot, I can connect to my mysql server with the following configuration, but I don't connect to my mysql server with vscode-sqltools.

Below is the data source configuration fragment for my spring boot project.

```
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lwk?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: lwk
    password: 123456
```

The following is a configuration file fragment generated when I create a mysql connection with vscode-sqltools. The current configuration file is /home/lwk/.config/Code/User/settings.json.

```
{
    "sqltools.connections": [
        {
            "connectionTimeout": 30,
            "database": "lwk",
            "dialect": "MySQL",
            "name": "mysql",
            "password": "123456",
            "port": 3306,
            "server": "127.0.0.1",
            "username": "lwk"
        }
    ]
}
```

**Desktop (please complete the following information):**
 - SQLTools Version: v 0.19.5
 - VSCode Version: 1.35.1
 - Dialect Used: MySQL
 - OS: Linux mint 19.1
 - MySQL Server Version: 8.0.16 MySQL Community Server
